[package]
name = "bevy_wry"
version = "0.1.5"
edition = "2021"
categories = ["bevy-plugin", "gui"]
description = "A tauri-apps/wry integration with Bevy engine"
keywords = ["bevy", "wry", "bevy_wry"]
license = "MIT"
authors = ["Pawel Bis"]
repository = "https://github.com/PawelBis/bevy_wry"

[dependencies]
wry = { version = "0.36", features = ["transparent", "devtools"] }
bevy = { version = "0.13", default_features = false, features = ["bevy_winit"] }
winit = "0.29"
thiserror = "1.0"
tungstenite = "0.21"
serde = "1.0"
serde_json = "1.0"
bincode = "1.3"

[[example]]
name = "simple"
path = "examples/simple.rs"
required-features = ["bevy/bevy_core_pipeline", "bevy/bevy_render", "bevy/bevy_sprite"]
