[package]
name = "bevy_wry"
version = "0.1.4"
edition = "2021"
categories = ["bevy-plugin", "gui"]
description = "A tauri-apps/wry integration with Bevy engine"
keywords = ["bevy", "wry", "bevy_wry"]
license = "MIT"
authors = ["Pawel Bis"]
repository = "https://github.com/PawelBis/bevy_wry"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wry = { version = "0.36", features = ["transparent", "devtools"] }
bevy = "0.13"
winit = "0.29"
thiserror = "1.0"
tungstenite = "0.21"
serde = "1.0"
serde_json = "1.0"
bincode = "1.3"
