name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - name: Install wry dependencies
      run: sudo apt-get update; sudo apt-get install -y libwebkit2gtk-4.1-dev
      if: runner.os == 'linux'
    - name: Build
      run: cargo build --verbose
      env:
        CARGO_INCREMENTAL: 0
    - name: Run tests
      run: cargo test --tests --verbose
    - name: Run cargo fmt
      run: cargo fmt -- --check
